version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: chart.js
    versions:
    - 2.9.4
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: lodash
    versions:
    - 4.17.20
