language: go

go:
  - 1.12.x
  - tip

before_install:
  - go get -t -v ./...
  - go get github.com/schrej/godacov

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  - godacov -t $CODACY_TOKEN -r ./coverage.txt -c $TRAVIS_COMMIT